apiVersion: v1
kind: Pod
metadata:
  labels:
    run: tools
  name: tools
  namespace: default
spec:
  containers:
  - image: tools:latest
    name: tools
    stdin: true
    env:
      - name: CONTAINER_NAME
        value: TOOLS POD
    securityContext:
      runAsUser: 10001
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      readOnlyRootFilesystem: true
      capabilities:
        drop:
          - ALL
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    imagePullPolicy: IfNotPresent
  dnsPolicy: ClusterFirst
  restartPolicy: Never
